# Generated by Django 5.1.6 on 2025-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='schedule',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
