# Generated by Django 5.1.6 on 2025-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0002_remove_entrepreneur_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='friday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='monday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='saturday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='sunday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='sunday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='thursday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='tuesday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='wednesday_close',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='wednesday_open',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
