# Generated by Django 5.1.6 on 2025-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0003_remove_entrepreneur_friday_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
