# Generated by Django 5.1.6 on 2025-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0004_entrepreneur_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='schedule',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='jueves',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='lunes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='martes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='miercoles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='viernes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
