# Generated by Django 5.1.6 on 2025-04-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0005_remove_entrepreneur_schedule_entrepreneur_jueves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='contact_info',
            field=models.CharField(default='No especificado', max_length=255),
            preserve_default=False,
        ),
    ]
